CREATE TABLE Usuarios(
	USUARIO_ID SERIAL PRIMARY KEY,
	USUARIO_NICKNAME VARCHAR(30) NOT NULL UNIQUE,
	USUARIO_NOME VARCHAR(100) NOT NULL
);

INSERT INTO Usuarios (USUARIO_NICKNAME , USUARIO_NOME) VALUES ('Casari' , 'Davi');

SELECT * FROM Usuarios